import { defaultValues } from './defaultValues';

export const tempJSON = {
    sections: [
        {
            name: 'personalDetails',
            label: 'Personal Details',
            transformX: 0,
            fields: [
                {
                    name: 'firstName',
                    type: 'text',
                    value: null,
                    required: true,
                    space: 0.5,
                    defaultValue: defaultValues['firstName'],
                },
                {
                    name: 'lastName',
                    type: 'text',
                    value: null,
                    required: true,
                    space: 0.5,
                    defaultValue: defaultValues['lastName'],
                },
                {
                    name: 'jobTitle',
                    type: 'text',
                    value: null,
                    required: true,
                    space: 1,
                    defaultValue: defaultValues['jobTitle'],
                },
                {
                    name: 'address1',
                    type: 'text',
                    value: null,
                    required: true,
                    label: 'Address 1',
                    space: 0.5,
                    maxLength: 15,
                    defaultValue: defaultValues['address1'],
                },
                {
                    name: 'address2',
                    type: 'text',
                    value: null,
                    label: 'Address 2',
                    space: 0.5,
                    maxLength: 15,
                    defaultValue: defaultValues['address2'],
                },
                {
                    name: 'phone',
                    type: 'text',
                    value: null,
                    space: 0.5,
                    defaultValue: defaultValues['phone'],
                },
                {
                    name: 'emailAddress',
                    type: 'text',
                    required: true,
                    value: null,
                    space: 0.5,
                    defaultValue: defaultValues['emailAddress'],
                },
            ],
        },
        {
            name: 'summary',
            transformX: 0,
            fields: [
                {
                    name: 'summary',
                    type: 'textarea',
                    value: null,
                    space: 1,
                    multiLineRows: 12,
                    defaultValue: defaultValues['summary'],
                },
            ],
        },
        {
            name: 'professionalExperience',
            label: 'Professional Experience',
            transformX: 0,
            fields: [
                {
                    name: 'positionTitle',
                    type: 'text',
                    value: null,
                    required: true,
                    space: 0.5,
                    defaultValue: defaultValues['positionTitle'],
                },
                {
                    name: 'companyName',
                    type: 'text',
                    value: null,
                    required: true,
                    space: 0.5,
                    defaultValue: defaultValues['companyName'],
                },
                {
                    name: 'location',
                    type: 'text',
                    value: null,
                    space: 0.5,
                    defaultValue: defaultValues['location'],
                },
                {
                    type: null,
                    space: 0.5,
                },
                {
                    name: 'startDate',
                    type: 'date',
                    value: null,
                    required: true,
                    space: 0.5,
                    defaultValue: defaultValues['startDate'],
                },
                {
                    name: 'endDate',
                    type: 'date',
                    value: null,
                    space: 0.5,
                    defaultValue: defaultValues['endDate'],
                },
                {
                    name: 'currentlyWorking',
                    type: 'checkbox',
                    value: null,
                    space: 0.5,
                    defaultValue: defaultValues['currentlyWorking'],
                },
                {
                    name: 'workSummary',
                    type: 'textarea',
                    value: null,
                    space: 1,
                    required: true,
                    multiLineRows: 12,
                    defaultValue: defaultValues['workSummary'],
                },
            ],
        },
        {
            name: 'educationDetails',
            label: 'Education',
            transformX: 0,
            fields: [
                {
                    name: 'schoolName',
                    type: 'text',
                    required: true,
                    value: null,
                    space: 0.5,
                    maxLength: 30,
                    defaultValue: defaultValues['schoolName'],
                },
                {
                    name: 'startDate',
                    type: 'date',
                    value: null,
                    required: true,
                    space: 0.5,
                },
                {
                    name: 'endDate',
                    type: 'date',
                    value: null,
                    space: 0.5,
                },
                {
                    name: 'degree',
                    type: 'text',
                    required: true,
                    value: null,
                    space: 0.5,
                },
                {
                    name: 'fieldOfStudy',
                    type: 'text',
                    required: true,
                    value: null,
                    space: 0.5,
                },
                {
                    name: 'description',
                    type: 'textarea',
                    required: true,
                    value: null,
                    space: 1,
                    multiLineRows: 6,
                },
            ],
        },
        {
            name: 'skills',
            label: 'Skills',
            transformX: 0,
            fields: [
                {
                    name: 'skill',
                    type: 'textarea',
                    required: true,
                    value: null,
                    space: 1,
                    multiLineRows: 6,
                },
            ],
        },
    ],
};
